### ISSUE TITLE
[Feature-Request]  Disable for current search by cliccking on icon!

### ISSUE THREAD

**Issue by skywinder** [klevstul/NoCountryRedirect#1]
Thanks, man, really missed thing in chrome!
Sometime I want to see local search anyway. It would be nice, if I can disable redirect to `.com` by clicking on icon.

**Comment by klevstul** [comment]
thank you for your feedback. feature request will be considered in upcoming version.

**Comment by skywinder** [comment]
Actually, NCR problem could be solved with modifying search engine, but in that case predictive search doesn't work.
FYI: http://superuser.com/questions/989149/no-country-redirect-predictive-search-search-suggestions-in-chrome-omnibox

**Comment by klevstul** [comment]
right, that is an alternative. this entire country specific redirection is annoying. glad there are ways around it.

**Comment by klevstul** [comment]
hi.

i am working on your request now. i have created an option to open a page with ncr disabled. the problem is that i do not know what tld (.no, .se, .pl etc) to choose. and since the url has been ncr-ified once, the next request will most likely be stuck on .com as well.

possible solutions:
- add an option field where you specify what tld you want to open disabled urls using
- add location tracking to the extension, to find out where users are
- let users manually change the url, from .com to desired tld.

i will go for option one, due to privacy issues.

**Comment by klevstul** [comment]
this has now been fixed, and version 1.2.1602 is being rolled out to all users in this very moment. thanks for your suggestion.

cheers,
frode.

**Comment by skywinder** [comment]
@klevstul awesome work! thank you! :+1:
