### ISSUE TITLE
OBSOLETE : Status icon in omnibox

### ISSUE THREAD

**Issue by EC-O-DE** [klevstul/NoCountryRedirect#26]
The status icon in omnibox could rather disappear when inactive. This behavior I've seen on many extensions, like Extension Source Viewer. 

The pop-up that's with the icon not sure if it functions like it should in Opera: there is activity/inactivity info and possibilities to open current page in incognito and open ext settings.

**Comment by klevstul** [comment]
thanks for reporting this.

the extensions work differently in chrome and opera. because in chrome the ncr icon is not in the omnibox at all. there all extensions are listed on the right side of the omnibox, by default. and you can hide it from the menu manually:
![image](https://user-images.githubusercontent.com/216850/28743744-0f7e27c8-7452-11e7-8408-ec60362f2dc8.png)

this is what the pop-up looks like on chrome:
![image](https://user-images.githubusercontent.com/216850/28743750-2f67ca1c-7452-11e7-9628-6127967816ca.png)

i will have to test this extension on opera, to see what i can do. however, i will not promise anything though, in case it's too time-consuming or tricky to fix.

**Comment by ZenFi** [comment]
Well this is the best omnibox extension to get google behave, so you would get I think a lot of support from Opera and Vivaldi users.

In opera there are extension icons listed right side of omnibox. But your ext just for some reason appears in omnibox. I can hide it from opera://extensions page but I kind of like it that it's visible when it's active.

**Comment by klevstul** [comment]
@ZenFi 
thanks for your feedback. i will look at it when i get some extra time on my hands.

**Comment by EC-O-DE** [comment]
In Opera (and some other Chromium browsers) page_action icon appears inside omnibox rather than on the right side of omnibox in address bar like in Chrome. The solution is to use browser_action.

https://dev.opera.com/extensions/browser-actions/

**Comment by klevstul** [comment]
@EC-O-DE 
thanks for the input. i will take a look!

**Comment by klevstul** [comment]
@EC-O-DE 
finally, i have some time on my hands to look at the ncr extension.

this one is a "wontfix". i want the ncr icon to show at all times as there is a feature being used for more than just "ncr'ified" pages:
![image](https://user-images.githubusercontent.com/216850/32601851-55eed6c4-c544-11e7-9e4a-99e7a67920b2.png)

notetoself:
https://developer.chrome.com/extensions/api_index
https://developer.chrome.com/extensions/browserAction
https://developer.chrome.com/extensions/pageAction

**Comment by klevstul** [comment]
relates #20
